### ISSUE TITLE
Mouse event turn off 

### ISSUE THREAD

**Issue by kismadar14** [ligius-/lenovo-backlight-control#2]
Hi dear developer!
I want to turning of the backlight on when i move the mouse. I want to the light on if just typing. Can i setting this function somewhere?
Thank you!

**Comment by ligius-** [comment]
Hi,

I think you can edit the .AHK script and replace _A_TimeIdle_ with _A_TimeIdleKeyboard_. I haven't tried it, but it should work.
https://www.autohotkey.com/docs/Variables.htm#TimeIdleKeyboard
Perhaps the idle timer in AHK can also be configured to ignore mouse events, which it should, by default, but somehow this did not work for me. Perhaps removing the line ;#InstallMouseHook can achieve this, even though it's commented out.

**Comment by kismadar14** [comment]
Thank you the help! Its function!
