### ISSUE TITLE
SetKeyboardBackLightStatus function params changed

### ISSUE THREAD

**Issue by figrn** [ligius-/lenovo-backlight-control#5]
Lenovo has pushed an update to **Keyboard_Core.dll** that changed the definition of the **SetKeyboardBackLightStatus** function - it now takes a second parameter of type **HidKbdData**. Inspecting the definition it appears that the second parameter can be null. An update is needed that passes null for the second parameter, without it an error of _System.Reflection.TargetParameterCountException: Parameter count mismatch_ occurs.

Below is the overview of the new function inspeted from JetBrains dotPeek:

```
public unsafe uint SetKeyboardBackLightStatus(int nStatus, HidKbdData hidKbdData) {
    if (hidKbdData != null) {
        ....
    } else {
        ....
    }
    return 0;
}

```

**Comment by SolUtain** [comment]
Good catch! I [forked](https://github.com/SolUtain/lenovo-backlight-control) this project and posted a fixed [release](https://github.com/SolUtain/lenovo-backlight-control/releases/tag/v02). I also created a [pull request](https://github.com/ligius-/lenovo-backlight-control/pull/6).

**Comment by ligius-** [comment]
Thank you, I have a newer Thinkpad, but will update the old one and see if I can confirm the issue. I would anyway want to replace the .exe with PowerShell, I've already tried it on my C940 and it works, though the usage there is a bit different.

**Comment by SolUtain** [comment]
For what it's worth, I am using a ThinkPad X1 Yoga Gen 3. The only change I've had to make for my own usage is changing the AutoHotkey script's _Keyboard_Core.dll_ location to _C:\ProgramData\Lenovo\ImController\Plugins\ThinkKeyboardPlugin\x86\Keyboard_Core.dll_, which is created by the Lenovo Vantage application. That change is included in the release I linked.

**Comment by figrn** [comment]
I can confirm that doing a new build with the "null" second parameter makes everything operational again.
- T490s Thinkpad (4 months old)
- Keyboard_Core.dll 2.0.0.15 (modified data 2020-12-01 9:10PM) 
- Path to Keyboard_Core.dll: %programdata%\Lenovo\ImController\Plugins\ThinkKeyboardPlugin\x86\

**Comment by ligius-** [comment]
I've tested the change, merged it and published a new exe file and script (v02). Thank you @figrn and @SolUtain .
