### ISSUE TITLE
ThinkPad T570 keyboard backlight stopped working recently

### ISSUE THREAD

**Issue by ghost** [ligius-/lenovo-backlight-control#7]
I'm looking for help setting up the keyboard backlight program on my ThinkPad T570.  It was working fine with version 1 but there must have been some recent Windows 10 update that screwed it up.  I followed the original directions and even tried them with version 2, which was placing both the thinkpadlight application and X230Backlight ahk files in the appropriate 86x folder.  I've also tried converting the ahk file to exe and running that but no success.  I added them to the startup folder as well but nothing works.  Also, the icon shows up in the system tray but still nothing.  I use Symantec and Malwarebytes but have the required files on the exception list, plus I've tried running them with both programs disabled.  Do you have exact step-by-step instructions since I have very little coding experience?  Any help would be appreciated.

**Comment by ghost** [comment]
Just FYI, I installed autohotkey with the unicode 32 version

**Comment by ligius-** [comment]
Can you check if the Keyboard_Core.dll file is at the same location? Mine has a size of 200592 bytes. See the properties of the file and confirm that the version is 2.0.0.15. If something is different, we can work on it together.

**Comment by roltean** [comment]
Hi ligius,

As I was saying in my other thread, I'm encountering the same issues on my P51. Keyboard_Core.dll is in the correct place and has that exact size and version that you just mentioned.
Also I tested your powershell script and it's working perfectly. I was able to set the illumination level with it from 0 to 1 to 2 without any problems. But AHK is still not working.

**Comment by ligius-** [comment]
Additionally, run "%SystemRoot%\SysWOW64\WindowsPowerShell\v1.0\powershell.exe" and type the following:
```
Add-Type -path "C:\Users\All Users\Lenovo\ImController\Plugins\ThinkKeyboardPlugin\x86\Keyboard_Core.dll"
(New-Object Keyboard_Core.KeyboardControl).SetKeyboardBackLightStatus
```
The output should look like:
```
PS C:\WINDOWS\SysWOW64\WindowsPowerShell\v1.0> (New-Object Keyboard_Core.KeyboardControl).SetKeyboardBackLightStatus    
OverloadDefinitions
-------------------
uint32 SetKeyboardBackLightStatus(int nStatus, HidKbdData hidKbdData)
```

If it looks differently, paste it here. If it looks the same, you can try running also:
```
(New-Object Keyboard_Core.KeyboardControl).SetKeyboardBackLightStatus(1, $null)
```
This should set a backlight level of 1, you can also try it with 0 and 2.

**Comment by ligius-** [comment]
@roltean are you using the latest AHK script? One of the last lines should read:
_Run, **thinkpadlightv02**.exe "c:\Users\All Users\Lenovo\ImController\Plugins\ThinkKeyboardPlugin\x86\Keyboard_Core.dll" %level% , , Hide_

You can also try running the exe manually using the parameters above (full path to DLL, level) and paste the output. It should write "0", i.e. success. A "1" denotes some error.

**Comment by roltean** [comment]
Yes. I'm using the new script. It has 2kb in size. Unlike the old one that has 4kb.
I also tried to execute your above command from cmd and got the following error:
```
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Users\myuser\Documents\Lenovo\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files (x86)\dotnet] or use the DOTNET_ROOT(x86) environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation].
```

**Comment by ligius-** [comment]
Thank you for the feedback. I had to change the build process to create a single executable (since the upgrade to Visual Studio) and set a target of NET5.0 for compilation. Can you try to install NET5.0? Alternatively, maybe just copying the attached file into the same folder as the .exe file should be enough.

https://dotnet.microsoft.com/download/dotnet/5.0 , see .NET Desktop Runtime 5.0.0:
x64: https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.0-windows-x64-installer
x86: https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.0-windows-x86-installer

**Comment by roltean** [comment]
Installing the x86 version of .NET 5.0 has fixed the issue.
Everything is now working perfectly again.
Thanks for the help!

**Comment by ligius-** [comment]
Thank you @roltean for the feedback. I will update the release notes.
@sfcwhs can you also try to follow the steps above and install the NET 5.0 runtime?

**Comment by ghost** [comment]
I'm running windows 10 but I should install x86 version?

**Comment by ligius-** [comment]
See https://support.microsoft.com/en-us/windows/32-bit-and-64-bit-windows-frequently-asked-questions-c6ca9541-8dce-4d48-0415-94a3faa2e13d how to check for the Windows version:

> Select the Start  button, then select Settings > System > About .
> Open About settings
> At the right, under Device specifications, see System type.

For 32-bit you need the x86 version, for 64-bit you need the x64 one.

**Comment by roltean** [comment]
Even though I have Windows 10 x64, installing the x64 version of .NET 5.0 did not fix the issue. Installing the x86 version did.

**Comment by ligius-** [comment]
Ah, good to know, thank you.

**Comment by ghost** [comment]
After installing dotnet, add both "thinkpadlightv02" and "X230Backlight" to plugin x86 folder and then startup folder?

**Comment by ghost** [comment]
my keyboard_core.dll version is correct but only 196kb in size

**Comment by ligius-** [comment]
You only need to add them both to the startup folder, or any folder.
For my setup, I added both files to a random folder and followed these instructions: https://www.autohotkey.com/docs/FAQ.htm#Startup

> Find the script file, select it, and press Control+C.
> Press Win+R to open the Run dialog, then enter shell:startup and click OK or Enter. This will open the Startup folder for the current user. To instead open the folder for all users, enter shell:common startup (however, in that case you must be an administrator to proceed).
> Right click inside the window, and click "Paste Shortcut". The shortcut to the script should now be in the Startup folder.

**Comment by ghost** [comment]
It's working again finally.  Thank you so much @ligius for your assistance.  I appreciate what you do!

**Comment by ghost** [comment]
One more question if you don't mind.  Is there a way to run the program before you sign into Windows so the keys light up while at the sign in screen?

**Comment by ligius-** [comment]
@sfcwhs I did not find a way to do this. The easiest option is to press Fn+Space.

Thank you both for your support in debugging this!
