### ISSUE TITLE
Thinkpad P51 still not working

### ISSUE THREAD

**Issue by roltean** [ligius-/lenovo-backlight-control#8]
thinkpadlightv02 is still not working for me on my Thinkpad P51. Any idea what might be causing this?
I replaced the ahk script and the exe with your latest versions and ... nothing. 
It used to work perfectly before with v01 and probably the older Lenovo drivers.

**Comment by ligius-** [comment]
I would say, at first sight, that this is a duplicate of https://github.com/ligius-/lenovo-backlight-control/issues/7
We can continue the discussion there and figure out a way to update the scripts/software.

**Comment by roltean** [comment]
Thank you! I'll move there and continue the conversation.
